#!/usr/bin/env bash
for i in {1..7}
do
	echo $i
done

#arithmetic evaluation
for (( i=1; i<=5; i++ ))
do
	echo $i
done

#parameter expansion
declare -a fruits=("apple" "banana" "cherry")
for i in ${fruits[@]}
do
	echo "today's fruit is: $i"
done 

#command substitution
for i in $(ls)
do
	echo "found a file: $i"
done




