#!/usr/bin/env bash
declare -a snacks=("apple" "banana" "orange")
snacks[5]="grapes"
snacks+=("mango")
echo ${snacks[@]}
#to discover empty elements
for i in {0..6}; do echo "$i: ${snacks[$i]}"; done
